<a href="https://colab.research.google.com/github/Jo-Minseok/DataProgramming/blob/main/Numpy_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **도전문제**

---



In [ ]:
#도전문제 3.1 다차원 배열 생성하기(난이도: 중)
#대각 성분이 모두 10인 4 X 4 크기의 다차원 배열을 생성하라.

np.eye(4,4)*10

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [ ]:
#도전문제 3.2 (난이도: 중)
#sin0도에서 sin180도 사이의 값 11개를 다음과 같이 출력하여라. 이때 sin()함수의 입력을 라디안을 사용하여라.(힌트: 넘파이의 linspace() 함수를 사용해보자. 라디안으로 180도는 np,pi를 사용하면 된다.)
#[0.00000000e+00 3.09016994e-01 5.87785252e-01 8.09016994e-01
# 9.51056516e-01 1.00000000e+00 9.51056516e-01 8.09016994e-01
# 5.87785252e-01 3.09016994e-01 1.22464680e-16]

a = np.linspace(0,np.pi,11)
print(np.sin(a))

[0.00000000e+00 3.09016994e-01 5.87785252e-01 8.09016994e-01
 9.51056516e-01 1.00000000e+00 9.51056516e-01 8.09016994e-01
 5.87785252e-01 3.09016994e-01 1.22464680e-16]


In [ ]:
#도전문제 3.3 (난이도: 하)
#b = np.array([[1, 1],[2, 2],[3, 3]])
#위의 b 배열에 insert(b,1,[1,2,3],axis=1)을 수행하고 그 결과를 출력하라.

b = np.array([[1,1],
             [2,2],
             [3,3]])
np.insert(b,1,[1,2,3],axis=1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
#도전문제 3.4 위의 결과를 수정하여 d 배열의 값이 axis 1, axis 0 방향에 대하여 각각 내림차순 정렬이 되도록 하고 그 결과를 출력하여라(힌트: 넘파이의 flip() 함수를 사용해보자.)
#array([[55,35,24],[69,19,9],[11,4,1]]), array([[4,1,9],[35,19,11],[69,24,55]])
#위의 결과: array([[1,4,11],
#                  [9,19,55],
#                  [24,35,69]])
result1=np.array([[35,24,55],[69,19,9],[4,1,11]])
result1.sort()
np.flip(result1, axis=0)
print(result1,'\n')

result2=np.array([[35,24,55],[69,19,9],[4,1,11]])
result2.sort(axis=0)
print(result2)

[[24 35 55]
 [ 9 19 69]
 [ 1  4 11]] 

[[ 4  1  9]
 [35 19 11]
 [69 24 55]]


In [ ]:
# 도전문제 3.5
# 1. 1에서 9까지의 모든 정수 값을 크기 순서대로 가지는 3x3 크기의 행렬 a를 arange()와 reshape()을 이용하여 생성하고, 모든 성분의 값이 3인 3x3 크기의 행렬 b를 full() 함수를 사용하여
# 생성한 다음, 다음과 같이 출력하라.
# a = [[1 2 3]
#      [4 5 6]
#      [7 8 9]]
# b = [[3 3 3]
#      [3 3 3]
#      [3 3 3]]
a = np.arange(1,10).reshape(3,3)
b = np.full((3,3),3)
print("a = ",a,'\n')
print("b = ",b)

a =  [[1 2 3]
 [4 5 6]
 [7 8 9]] 

b =  [[3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
# 도전문제 3.6(난이도:중)
# arange()를 사용하여 1에서 50까지의 원소를 가지는 다차원 배열을 만들자. 이 배열의 원소 50개를 랜덤하게 섞은 후 80%의 데이터는 train_data에 넣고 나머지 20%의 데이터는
# test_data라는 배열에 넣어서 이 두 배열을 반환하는 함수 train_test_split()을 만들자. 반환된 배열 값을 각각 출력하여라.
def train_test_split(a,per80):
  train_data = a[:per80]
  test_data = a[per80:]
  print("train_data_ = ",train_data,'\n')
  print("test_data_ = ",test_data)

a = np.arange(1,51)
per80 = int(np.size(a)*0.8)
per20 = int(np.size(a)*0.2)
np.random.shuffle(a)
train_test_split(a,per80)

train_data_ =  [16 14 49 41 47 45 40 10  5  6 12 44 36 26 50 30 17 19 32 13 28  3 48 11
 33 42 21  4  1  7 22 24 39 23 46 29 20  8 43 31] 

test_data_ =  [35 38 25 37  2 34 27 15  9 18]


In [ ]:
# 도전문제 3.7: 다차원 행렬의 생성과 활용(난이도: 중)
# 1.다음과 같은 연립방정식의 해를 numpy.linalg의 solve() 함수를 사용하여 구하여라.
# x + y - z = 0
# 2x - y + 3z = 9
# x + 2y + z = 8

a = np.array([[1,1,-1],
              [2,-1,3],
              [1,2,1]])
b = np.array([0,9,8])
print(np.linalg.solve(a,b))

# 2. 1번 문제의 연립방정식은 다음과 같은 행렬 A를 가진다.
# A = np.array([[1,1,-1],[2,-1,3],[1,2,1]],dtype='int32')
# 이 행렬의 행렬식을 linalg.det() 함수를 사용하여 다음과 같이 구하여라.
# det(A) = -11.0
print("dat(A) = %.1f"%np.linalg.det(a))


[1. 2. 3.]
dat(A) = -11.0


### **심화문제**

---





In [ ]:
#3.1다음의 기능을 넘파이를 사용하여 구현하시오.
#1) numpy의 arange()함수를 사용하여 1에서 45까지의 연속적인 번호를 생성하여라.
#[ 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]
import numpy as np
np.arange(0,46)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [ ]:
#2) 랜덤 씨드값을 85로 설정하여라. 그런 다음 이 배열을 랜덤하게 섞어서(shuffle) 첫 6개의 숫자를 슬라이싱 하라. 그 결과를 lotto라는 변수에 할당한 후, 다음과 같이 출력하라.
#lotto = [22 9 15 44 39 37]
np.random.seed(85)
a = np.random.randint(45,size=45)
lotto = a[0:6]
print(a)
print("lotto =",lotto)

[42 32 13  4 13 19 37 15 33 24 29  3 27 11  6 32 39 28 29 39 25  9 38 44
 19 22 44 42 30 34 12 21 41 36 11 15 31 35 44 16  9  9 12 16 12]
lotto = [42 32 13  4 13 19]


In [ ]:
#3) lotto 배열을 정렬한 후 출력하고 추가번호를 출력하라. 추가번호는 7번째 숫자를 출력하라.
lotto.sort()
plus = a[6]
print("lotto =",lotto,", 추가번호 =",plus)

lotto = [ 4 13 13 19 32 42] , 추가번호 = 37


In [ ]:
#4) 다음과 같이 0에서 24까지의 값을 가지는 5 X 5 크기의 2차원 행렬 n_arr을 생성하여라
#[[ 0 1 2 3 4]
# [ 5 6 7 8 9]
# [10 11 12 13 14]
# [15 16 17 18 19]
# [20 21 22 23 24]]
n_arr=np.arange(25).reshape(5,5)
print(n_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#5) 앞서 만든 n_arr의 가장 첫 원소와 가장 마지막 원소를 인덱싱하여 다음과 같이 출력하여라. 이때, 마지막 원소의 인덱싱은
#반드시 음수 값을 사용하여라.
#첫 원소 : 0
#마지막 원소 : 24
print("첫 원소 :",n_arr[0,0])
print("마지막 원소 :",n_arr[-1,-1])

첫 원소 : 0
마지막 원소 : 24


In [ ]:
#6) n_arr 배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성하여라.
#[[0 1 2 3 4]
#[5 6 7 8 9]]
answer=n_arr[0:2,:]
print(answer)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#7) n_arr 배열에 슬라이싱을 적용하여 다음과 같은 값을 가지는 배열을 생성하여라.
#[[ 0 2 4]
#[ 5 7 9]
#[10 12 14]
#[15 17 19]
#[20 22 24]]
answer = n_arr[:,::2]
print(answer)

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


In [ ]:
#8) n_arr 배열에 슬라이싱을 적용한 후, reshape()을 적용하여 다음과 같은 값을 가지는 배열을 생성하여라.
#[[0 1]
#[2 3]
#[4 5]
#[6 7]
#[8 9]]
print(n_arr[0:2,:].reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#3.2 다음과 같이 난수로 이루어진 2x2x2 형태의 배열 a를 생성하여라.
#array([[[   0.090924591,   -0.34474798],
#        [  -0.93602735,    0.45142614]],

#        [[ -0.83522591,   1.43767399],
#         [ -0.08459385,   0.35577307]]])
a = np.random.randn(8).reshape(2,2,2)
a

array([[[-0.9442699 ,  1.13037816],
        [-0.67865074,  0.05602191]],

       [[ 2.26629148,  0.90764928],
        [-1.08898305, -0.18553942]]])

In [ ]:
#1) a 배열에서 max() 메소드를 사용하여 가장 큰 값을 구하여 다음과 같이 출력하라.
# a 배열의 최대값 : 1.4376739942182297
print("a 배열의 최대값 :",a.max())

a 배열의 최대값 : 2.2662914771454723


In [ ]:
#2) a 배열에서 min() 메소드를 사용하여 가장 작은 값을 구한 다음 출력하여라.
# a 배열의 최소값 : -0.9360273546035357
print("a 배열의 최소값 :",a.min())

a 배열의 최소값 : -1.0889830522031287
